### ISSUE TITLE
Make Figma template - Community Board

### ISSUE THREAD

**Issue by anaiscmateus** [Resilient-Labs/nourish#10]

**Comment by alejandralondev** [comment]
Finished first draft of Figma template for the community board
<img width="296" alt="message-board-0" src="https://github.com/Resilient-Labs/nourish/assets/145242183/30c77d47-7ff2-4b01-a282-c80ed9a11444">

**Comment by alejandralondev** [comment]
second draft - took out task board for now until we solidify the admin concept and if scope of work fits into our timeline
<img width="464" alt="message-board" src="https://github.com/Resilient-Labs/nourish/assets/145242183/05898c11-70c7-4abe-a65c-2b80f88342f6">
