### ISSUE TITLE
Make Figma template - Sign Up/Log In

### ISSUE THREAD

**Issue by xsarahyu** [Resilient-Labs/nourish#13]

**Comment by codedbycass** [comment]
Simple login and sign up pages, no styling and placeholder images

<img width="349" alt="Screenshot 2023-12-19 at 11 31 44 AM" src="https://github.com/Resilient-Labs/nourish/assets/122684139/75aa2459-bb73-4eef-bc00-add07f102b9c">

**Comment by codedbycass** [comment]
/signup option 2, volunteer onboarding and an admin checkbox should we need to add that role. front end team still figuring it out.
<img width="355" alt="Screenshot 2023-12-19 at 11 31 53 AM" src="https://github.com/Resilient-Labs/nourish/assets/122684139/21aa38ef-8183-4fbf-a1d1-bea9369d6bfd">

**Comment by codedbycass** [comment]
FAQ page, only has the core right now. Advocated for toggle question/answers to reduce large amounts of text on screen to improve user experience

<img width="348" alt="Screenshot 2023-12-19 at 11 32 08 AM" src="https://github.com/Resilient-Labs/nourish/assets/122684139/7904d604-dbfc-4b20-8ea2-0bc090cba33e">
