### ISSUE TITLE
Review fridges collection in DB

### ISSUE THREAD

**Issue by JacinthaDev** [Resilient-Labs/nourish#53]

**Comment by RoReeceDev** [comment]
If you guy send me your emails for mongodb I can add you to the database

**Comment by anaiscmateus** [comment]
@RoReeceDev Hey! My email is anaismateusc@gmail.com

**Comment by briannawillis195** [comment]
@RoReeceDev my email is brianna.willis195@gmail.com

**Comment by AymanDevOps** [comment]
Hey my email is aymanadevops@gmail.com

**Comment by RoReeceDev** [comment]
@anaiscmateus @briannawillis195 @AymanDevOps You should have access to Database now, let me know if there are any issues.
